version: '3.5'

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: kirya
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema  # Название бд
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: # docker exec -it tesak psql -U tkach -d cinema, после \du или \l