from . import db


class users(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(300), nullable=False)
    username = db.Column(db.String(30), unique=True, nullable=False)
    password = db.Column(db.String(500), nullable=False)


class cinema_sessions(db.Model):
    session_id = db.Column(db.Integer, primary_key=True)
    movie = db.Column(db.String(300), nullable=False)
    start_time = db.Column(db.TIMESTAMP, nullable=False)
    seat_1 = db.Column(db.Boolean, default=False)
    seat_2 = db.Column(db.Boolean, default=False)
    seat_3 = db.Column(db.Boolean, default=False)
    seat_4 = db.Column(db.Boolean, default=False)
    seat_5 = db.Column(db.Boolean, default=False)
    seat_6 = db.Column(db.Boolean, default=False)
    seat_7 = db.Column(db.Boolean, default=False)
    seat_8 = db.Column(db.Boolean, default=False)
    seat_9 = db.Column(db.Boolean, default=False)
    seat_10 = db.Column(db.Boolean, default=False)
    seat_11 = db.Column(db.Boolean, default=False)
    seat_12 = db.Column(db.Boolean, default=False)
    seat_13 = db.Column(db.Boolean, default=False)
    seat_14 = db.Column(db.Boolean, default=False)
    seat_15 = db.Column(db.Boolean, default=False)
    seat_16 = db.Column(db.Boolean, default=False)
    seat_17 = db.Column(db.Boolean, default=False)
    seat_18 = db.Column(db.Boolean, default=False)
    seat_19 = db.Column(db.Boolean, default=False)
    seat_20 = db.Column(db.Boolean, default=False)
    seat_21 = db.Column(db.Boolean, default=False)
    seat_22 = db.Column(db.Boolean, default=False)
    seat_23 = db.Column(db.Boolean, default=False)
    seat_24 = db.Column(db.Boolean, default=False)
    seat_25 = db.Column(db.Boolean, default=False)
    seat_26 = db.Column(db.Boolean, default=False)
    seat_27 = db.Column(db.Boolean, default=False)
    seat_28 = db.Column(db.Boolean, default=False)
    seat_29 = db.Column(db.Boolean, default=False)
    seat_30 = db.Column(db.Boolean, default=False)
    client_1 = db.Column(db.String(300), default=None)
    client_2 = db.Column(db.String(300), default=None)
    client_3 = db.Column(db.String(300), default=None)
    client_4 = db.Column(db.String(300), default=None)
    client_5 = db.Column(db.String(300), default=None)
    client_6 = db.Column(db.String(300), default=None)
    client_7 = db.Column(db.String(300), default=None)
    client_8 = db.Column(db.String(300), default=None)
    client_9 = db.Column(db.String(300), default=None)
    client_10 = db.Column(db.String(300), default=None)
    client_11 = db.Column(db.String(300), default=None)
    client_12 = db.Column(db.String(300), default=None)
    client_13 = db.Column(db.String(300), default=None)
    client_14 = db.Column(db.String(300), default=None)
    client_15 = db.Column(db.String(300), default=None)
    client_16 = db.Column(db.String(300), default=None)
    client_17 = db.Column(db.String(300), default=None)
    client_18 = db.Column(db.String(300), default=None)
    client_19 = db.Column(db.String(300), default=None)
    client_20 = db.Column(db.String(300), default=None)
    client_21 = db.Column(db.String(300), default=None)
    client_22 = db.Column(db.String(300), default=None)
    client_23 = db.Column(db.String(300), default=None)
    client_24 = db.Column(db.String(300), default=None)
    client_25 = db.Column(db.String(300), default=None)
    client_26 = db.Column(db.String(300), default=None)
    client_27 = db.Column(db.String(300), default=None)
    client_28 = db.Column(db.String(300), default=None)
    client_29 = db.Column(db.String(300), default=None)
    client_30 = db.Column(db.String(300), default=None)
